[package]
name = "gh-pr-stats"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
gql_client = "1.0.7"
serde = "1.0.210"
tabled = "0.16.0"
tokio = { version = "1.40.0", features = ["full"] }
